### ISSUE TITLE
Add mozilla-django-oidc-db[setupconfig] as dependancy

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-api-framework#43] opened 2024-07-10 12:50 UTC
### Thema / Theme

Other

### Omschrijving / Description

After merging in this PR, we need to include this optional dependancy in OAf

https://github.com/maykinmedia/mozilla-django-oidc-db/pull/115/files

**Comment by Coperh** [comment] 2024-08-27 10:25
Duplicate of #23

**Closed by Coperh** 2024-08-27 10:25 UTC
Labels: enhancement, owner: dimpact
